### ISSUE TITLE
Error when using with nextjs

### ISSUE THREAD

**Issue by lohazo** [staltz/use-profunctor-state#2]
This is [Codesandbox](https://codesandbox.io/s/n3w6p7krw4) with error

**Comment by staltz** [comment]
What does nextjs docs say about using hooks?

**Comment by lohazo** [comment]
I can use all other hooks in nextjs without any problem

**Comment by staltz** [comment]
Odd, because useProfunctorState calls a hook too.

**Comment by simonmoog** [comment]
I get more or less than same error with a vanilla CRA project. Could this be because use-profunctor-state is using an outdated Hooks API?

**Comment by audionerd** [comment]
I was also getting the error `Invariant Violation: Hooks can only be called inside the body of a function component`. Compiling with React v16.8.6 seemed to fix it.

**Comment by staltz** [comment]
Try version 1.2.0 :)
